artean:
    resource: "@CuatrovientosArteanBundle/Resources/config/routing.yml"
    prefix:   /
    
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_assetic:
    resource: .
    type:     assetic
